### ISSUE TITLE
特性提议：可打开页面自动刷新或配置为自动刷新

### ISSUE THREAD

**Issue by winter60** [weihan-Chen/WordCounter#1]
每次打开统计页面，还要点一下按钮，着实有丢丢不方便~
挂件写得挺好，孩子每天都在用👍

**Comment by Ultrasonicer** [comment]
V0.0.4.20220624重构为自动间隔刷新
感谢反馈，请关注下自动刷新可能存在的性能问题

**Comment by Ultrasonicer** [comment]
重新实现了一下，现在支持手动刷新和自动刷新开关

**Comment by Ultrasonicer** [comment]
现在支持三种模式选择，手动、自动间隔、自动实时
