### ISSUE TITLE
思源进入`暗黑`模式时，挂件并未自动切换到该模式下的视图

### ISSUE THREAD

**Issue by QMike0** [weihan-Chen/WordCounter#5]
问题如题所示。
在自行改动WordCounter挂件的外观时，偶然在`index.css`中发现它原来支持思源暗黑/明亮模式下，视图配色的切换：
（查GPT才看懂的...）
```
@media (prefers-color-scheme: dark) {
	body {
		background-color: #1e1e1e;
		color: rgb(255, 255, 255);
	}
}
@media (prefers-color-scheme: light) {
	body {
		background-color: rgb(255, 255, 255);
		color: rgb(0, 0, 0);
	}
}
```
然而实际转入`暗黑`模式后，WordCounter的背景配色并非自动切换到黑色，应该是哪里存在问题。
![image](https://github.com/Ultrasonicer/WordCounter/assets/43239563/6d73dd65-ab73-4460-878a-dcedfa3d2a14)
大佬有空看下能不能修改成功，就当是改正一下美中不足了

**Comment by Ultrasonicer** [comment]
fixed. [Ref: V0.0.9](https://github.com/Ultrasonicer/WordCounter/releases/tag/V0.0.9)
暂时未提供自定义颜色功能，有能力的可以自行在CSS文件中选择颜色。😊
